@startuml

Usuário as usr

usr -right-> (manter informações pessoais)
usr -left-> (logar)
usr -up-> (adicionar amigo)
usr -up-> (desfazer amizade)
usr -up-> (trocar mensagens diretas)
usr -down-> (trocar mensagens em grupo)
usr -down-> (postar no perfil)
usr -left-> (postar em um grupo)
usr -down-> (pesquisar amigos)

@enduml