@startuml

skinparam shadowing false

class Usuario {
    str nome
    str apelido
    str email
    int idade
    list<Mensagem> notificacoes
    list<Conversa> conversas
    list<Postagem> feed

    postar_no_perfil()
    enviar_convite_amizade()
    desfazer_amizade()
}

class Conversa {
    list<Usuario> participantes
    list<Mensagem> mensagens

    enviar_mensagem()
}

class Mensagem {
    str conteudo
    Usuario dono
    datetime momento
}

Usuario "2..n"-right-"0..n" Conversa: participa de
(Usuario, Conversa) .. Mensagem

class Postagem {
    str conteudo
    str assunto
    datetime momento
    Usuario dono
    bool eh_publico
}

Usuario "1 "--"0..n " Postagem: " tem"

class Grupo {
    list<Usuario> integrantes
    list<Usuario> administradores
    list<Postagem> postagens
    bool eh_publico

    postar()
    solicitar_entrada()
    adicionar_membro()
    remover_membro()
    tornar_admin()
}

Usuario "1..n "-down-"0..n " Grupo: participa de
(Usuario, Grupo) .. Postagem

@enduml